name: scandit_flutter_datacapture_parser
description: Scandit Data Capture SDK for Flutter. ScanditParser implements the parsing capabilities of the Scandit Data Capture SDK.
version: 6.14.0
homepage: https://scandit.com



environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  scandit_flutter_datacapture_core:
    '>=6.14.0 <6.14.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  effective_dart: ^1.3.1

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.parser
        pluginClass: ScanditFlutterDataCaptureParserProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureParserPlugin
