name: scandit_flutter_datacapture_parser
description: This plugin implements the parsing capabilities of the Scandit Data Capture SDK.
version: 7.1.1
homepage: https://scandit.com



environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  scandit_flutter_datacapture_core:
    '>=7.1.1 <7.1.2'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.parser
        pluginClass: ScanditFlutterDataCaptureParserProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureParser
