name: scandit_flutter_datacapture_parser
description: Scandit Data Capture SDK for Flutter. ScanditParser implements the parsing capabilities of the Scandit Data Capture SDK.
version: 6.17.2
homepage: https://scandit.com



environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.3"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  scandit_flutter_datacapture_core:
    '>=6.17.2 <6.17.3'

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  linter: ^1.30.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scandit.datacapture.flutter.parser
        pluginClass: ScanditFlutterDataCaptureParserProxyPlugin
      ios:
        pluginClass: ScanditFlutterDataCaptureParserPlugin
